export default function() {
    return [
        {number: '1st', room: 101, floor: '1st', name: 'dummy1', table: 'dummy1', graph: 'dummy1'},
        {number: '2nd', room: 101, floor: '1st', name: 'dummy2', table: 'dummy2', graph: 'dummy2'},
        {number: '3rd', room: 101, floor: '1st', name: 'dummy3', table: 'dummy3', graph: 'dummy3'},
        {number: '4th', room: 101, floor: '1st', name: 'dummy4', table: 'dummy4', graph: 'dummy4'},
        {number: '5th', room: 101, floor: '1st', name: 'dummy5', table: 'dummy5', graph: 'dummy5'},
        {number: '6th', room: 101, floor: '1st', name: 'dummy6', table: 'dummy6', graph: 'dummy6'},
        {number: '1st', room: 102, floor: '1st', name: 'dummy7', table: 'dummy7', graph: 'dummy7'},
        {number: '2nd', room: 102, floor: '1st', name: 'dummy8', table: 'dummy8', graph: 'dummy8'},
        {number: '3rd', room: 102, floor: '1st', name: 'dummy9', table: 'dummy9', graph: 'dummy9'},
        {number: '4th', room: 102, floor: '1st', name: 'dummy10', table: 'dummy10', graph: 'dummy10'},
        {number: '5th', room: 102, floor: '1st', name: 'dummy11', table: 'dummy11', graph: 'dummy11'},
        {number: '1st', room: 103, floor: '1st', name: 'dummy12', table: 'dummy12', graph: 'dummy12'},
        {number: '2nd', room: 103, floor: '1st', name: 'dummy13', table: 'dummy13', graph: 'dummy13'},
        {number: '3rd', room: 103, floor: '1st', name: 'dummy14', table: 'dummy14', graph: 'dummy14'},
        {number: '4th', room: 103, floor: '1st', name: 'dummy15', table: 'dummy15', graph: 'dummy15'},
        {number: '5th', room: 103, floor: '1st', name: 'dummy16', table: 'dummy16', graph: 'dummy16'},
        {number: '1st', room: 104, floor: '1st', name: 'dummy17', table: 'dummy17', graph: 'dummy17'},
        {number: '2nd', room: 104, floor: '1st', name: 'dummy18', table: 'dummy18', graph: 'dummy18'},
        {number: '3rd', room: 104, floor: '1st', name: 'dummy19', table: 'dummy19', graph: 'dummy19'},
        {number: '4th', room: 104, floor: '1st', name: 'dummy20', table: 'dummy20', graph: 'dummy20'},
        {number: '5th', room: 104, floor: '1st', name: 'dummy21', table: 'dummy21', graph: 'dummy21'},
        {number: '1st', room: 201, floor: '2nd', name: 'dummy22', table: 'dummy22', graph: 'dummy22'},
        {number: '1st', room: 202, floor: '2nd', name: 'dummy23', table: 'dummy23', graph: 'dummy23'},
        {number: '1st', room: 203, floor: '2nd', name: 'dummy24', table: 'dummy24', graph: 'dummy24'},
        {number: '1st', room: 301, floor: '3rd', name: 'dummy25', table: 'dummy25', graph: 'dummy25'},
        {number: '1st', room: 302, floor: '3rd', name: 'dummy26', table: 'dummy26', graph: 'dummy26'},
        {number: '1st', room: 401, floor: '4th', name: 'dummy27', table: 'dummy27', graph: 'dummy27'},
    ];
}